In [1]:
import torch

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,7,8,9])
vector.shape

torch.Size([4])

In [13]:
scalar.ndim

0

In [15]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
matrix.shape

torch.Size([2, 3])

In [17]:
matrix.ndim

2

In [21]:
matrix[0].ndim

1

In [26]:
randa = torch.rand(3,5)

randa

tensor([[0.2378, 0.4836, 0.7906, 0.3067, 0.0607],
        [0.7656, 0.9123, 0.2598, 0.2135, 0.1826],
        [0.9688, 0.3868, 0.6736, 0.3679, 0.0261]])

In [27]:
# rand_tensor = torch.rand(6,8,, names=)
rand_img_tensor = torch.rand(224, 224, 3)
rand_img_tensor.shape, rand_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [28]:
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [29]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

In [35]:
one2ten = torch.arange(0, 10)

In [36]:
zeroslike = torch.zeros_like(one2ten)
zeroslike

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
oneslike = torch.ones_like(one2ten)
oneslike.size()

torch.Size([10])

In [40]:
oneslike.shape

torch.Size([10])

In [70]:
x = torch.arange(1., 101., step=10)
x

tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])

In [71]:
x.shape

torch.Size([10])

In [72]:
a = x.reshape(2,5)
a

tensor([[ 1., 11., 21., 31., 41.],
        [51., 61., 71., 81., 91.]])

In [73]:
a[:,0] = 100
a

tensor([[100.,  11.,  21.,  31.,  41.],
        [100.,  61.,  71.,  81.,  91.]])

In [74]:
x

tensor([100.,  11.,  21.,  31.,  41., 100.,  61.,  71.,  81.,  91.])

In [75]:
b = x.view(2,5)
b

tensor([[100.,  11.,  21.,  31.,  41.],
        [100.,  61.,  71.,  81.,  91.]])

In [76]:
b[:,1] = 200
b

tensor([[100., 200.,  21.,  31.,  41.],
        [100., 200.,  71.,  81.,  91.]])

In [67]:
x

tensor([100., 200.,  21.,  31.,  41.,  51.,  61.,  71.,  81.,  91.])

In [85]:
z = torch.zeros(3,2)
y = z.reshape(6)
y

tensor([0., 0., 0., 0., 0., 0.])

In [86]:
x = z.t().reshape(6)
x

tensor([0., 0., 0., 0., 0., 0.])

In [87]:
z.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [88]:
y

tensor([1., 1., 1., 1., 1., 1.])

In [89]:
x

tensor([0., 0., 0., 0., 0., 0.])

In [90]:
a = torch.arange(1, 61)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60])

In [91]:
b = a.reshape(3,4,5)

b

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40]],

        [[41, 42, 43, 44, 45],
         [46, 47, 48, 49, 50],
         [51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60]]])

In [92]:
b.shape

torch.Size([3, 4, 5])

In [93]:
c = b.permute(2,0 ,1)
c

tensor([[[ 1,  6, 11, 16],
         [21, 26, 31, 36],
         [41, 46, 51, 56]],

        [[ 2,  7, 12, 17],
         [22, 27, 32, 37],
         [42, 47, 52, 57]],

        [[ 3,  8, 13, 18],
         [23, 28, 33, 38],
         [43, 48, 53, 58]],

        [[ 4,  9, 14, 19],
         [24, 29, 34, 39],
         [44, 49, 54, 59]],

        [[ 5, 10, 15, 20],
         [25, 30, 35, 40],
         [45, 50, 55, 60]]])